version: '3'

services:
  spring-boot-rest-api-app:
    image: ss-rest-service-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app